name: Auto Merge Main to Testing

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            token:${{secrets.Actions_Part}}

      - name: Configure Git
        run: |
          git config --global user.name 'harshavardhanare'
          git config --global user.email 'harshachowdary35@gmail.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge main into testing
        run: |
          git checkout testing
          git merge -X theirs main --allow-unrealated-histories
          git push origin testing